title: Scientific Calculator
theme: jekyll-theme-cayman
description: A GitHub Pages site for the scientific calculator project.

author:
name: Eugenio cabral
email: kalefcabral@gmail.com

puglins:
    jekyll-seo-tag
    jekyll-feed
    jekyll-sitemap